name: culvertvision
channels:
  - conda-forge
dependencies:
  - python=3.11
  - black
  - flake8
  - isort
  - pip
  - typer
  - loguru
  - tqdm
  - pydantic
  - pydantic-settings
  - requests
  - gdal
  - libgdal-arrow-parquet
  - qgis
  - pip:
    - python-dotenv
    - -e .
